### ISSUE TITLE
mysql delete from subselect 

### ISSUE THREAD

**Issue by Breggor** [axelor/axelor-open-platform#18]
2018-03-05 09:37:51.128 DEBUG 6113 --- [           main] org.hibernate.SQL                        : delete from meta_view_custom where id in (select metaviewcu1_.id from meta_view_custom metaviewcu1_ where metaviewcu1_.name=?)
2018-03-05 09:37:51.135 DEBUG 6113 --- [           main] o.h.engine.jdbc.spi.SqlExceptionHelper   : could not execute statement [n/a]
java.sql.SQLException: You can't specify target table 'meta_view_custom' for update in FROM clause
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:964)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2501)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:205)
	at org.hibernate.hql.internal.ast.exec.BasicExecutor.doExecute(BasicExecutor.java:90)
	at org.hibernate.hql.internal.ast.exec.BasicExecutor.execute(BasicExecutor.java:59)
	at org.hibernate.hql.internal.ast.exec.DeleteExecutor.execute(DeleteExecutor.java:110)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.executeUpdate(QueryTranslatorImpl.java:437)
	at org.hibernate.engine.query.spi.HQLQueryPlan.performExecuteUpdate(HQLQueryPlan.java:374)
	at org.hibernate.internal.SessionImpl.executeUpdate(SessionImpl.java:1510)
	at org.hibernate.query.internal.AbstractProducedQuery.doExecuteUpdate(AbstractProducedQuery.java:1526)
	at org.hibernate.query.internal.AbstractProducedQuery.executeUpdate(AbstractProducedQuery.java:1504)
	at com.axelor.db.Query.delete(Query.java:457)
	at com.axelor.meta.service.MetaService.removeCustomViews(MetaService.java:491)
	at com.axelor.meta.service.MetaService$$EnhancerByGuice$$a82ea333.CGLIB$removeCustomViews$3(<generated>)
	at com.axelor.meta.service.MetaService$$EnhancerByGuice$$a82ea333$$FastClassByGuice$$26469b0.invoke(<generated>)
	at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:76)
	at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:62)
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:77)
	at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:55)
	at com.axelor.meta.service.MetaService$$EnhancerByGuice$$a82ea333.removeCustomViews(<generated>)
	at com.axelor.meta.loader.ViewLoader.importView(ViewLoader.java:247)
	at com.axelor.meta.loader.ViewLoader.importView(ViewLoader.java:178)
	at com.axelor.meta.loader.ViewLoader.process(ViewLoader.java:156)
	at com.axelor.meta.loader.ViewLoader.doLoad(ViewLoader.java:115)

**Comment by beuss** [comment]
Hi,
I think ADK is only supposed to work with PostgreSQL

**Comment by madmath03** [comment]
Based on the [documentation](http://docs.axelor.com/adk/latest/dev_guide/application/config.html#database-settings), it should work with MySQL if you setup `application.properties` properly.

Did you setup `db.default.driver = com.mysql.jdbc.Driver`?

Although it's not documented in ADK, Axelor Business Suite also defines the dialect. So for MySQL, it would be something like that:
`db.default.dialect = org.hibernate.dialect.MySQL5InnoDBDialect`
Not sure if it's still needed though...

**Comment by axeloradmin** [comment]
Initial support for MySQL was added in v4 but was not tested extensively. The upcoming v5 has better MySQL support. We would like to get community help to have first class MySQL support. We welcome contributions in this area.

Please sign the [CLA](https://github.com/axelor/axelor-development-kit/blob/master/CONTRIBUTING.md#contributor-license-agreement) and submit pull requests to improve MySQL support.

BTW, we'll check the issue but it is not the priority right now.

**Comment by axeloradmin** [comment]
The issue has been fixed in latest release 5.0.3.
